### ISSUE TITLE
zabbix server upgrade breaks <hostname>.error reading

### ISSUE THREAD

**Issue by sandrobordacchini** [yurtesen/zabbix_backuppc#8] opened 2023-03-04 23:39 UTC
I don't know if this is a real bug but i'd like to share this.

I have a well functioning zabbix 6.x (installed with packages) on a debian 11.
This zabbix monitors (also) a backuppc host with tens of backupped hosts.
I upgraded (via apt) the zabbix server (zabbix-agent, zabbix-frontend-php, zabbix-nginx-conf, zabbix-release, zabbix-server-pgsql, zabbix-sql-scripts) from version 1:6.0.5-1+debian11 up to version 1:6.0.13-1+debian11.
All the Error triggers for every host backupped by the backuppc host activated! (and still are...)

All the other readings are ok... only the error status (for every host) changed:
![image](https://user-images.githubusercontent.com/47782768/222933053-294be25e-3518-42c3-9e0c-f82a47f9c243.png)
The server has been upgraded at 17:45. The triggers activated at 18:19.

Please note that i did not touched the backuppc host so far.
I tried, later, to upgrade also the agent2 on backuppc, to avoid a (server-agent) version mismatch. The upgrade went well, but no change.

I checked the json returned to the _/index.cgi?action=metrics_ call on the backuppc system, dumping http traffic on localhost.
Every host actually contains ... `,"error":null,` ...

**Comment by yurtesen** [comment] 2023-03-07 08:18
Please report this to Zabbix forum https://www.zabbix.com/forum/ . There might be some issues with the preprocessing. Obviously if it can't fetch JSON, it won't work...

**Comment by sandrobordacchini** [comment] 2023-03-07 11:56
I will report it on the Zabbix forum, thank you @yurtesen 

Anyway I think I was not clear enough.

The JSON is returned correctly from backuppc to the agent.
Furthermore, i think it has always been, because i did not change anything on the monitored backuppc host, at first.
So I think that backuppc always returned "_null_" as the error field to the agent.

I think that what changed is the how this _null_ is seen by the zabbix server.
With the old version, it was probably seen like a "semantic" null, so its **strlen** is zero (cfr. https://github.com/yurtesen/zabbix_backuppc/blob/main/Template%20App%20BackupPC%20by%20Zabbix%20agent.xml#L730 )
With the new version, it is probably seen like a string "_null_" ... so its strlen is four (and enables the trigger).

That's my guess, and if you look to the item's history you probably will agree with me... what do you think?

**Comment by sandrobordacchini** [comment] 2023-03-07 12:23
Ok, someone already filed a bug report on zabbix https://support.zabbix.com/browse/ZBX-22130

**Comment by yurtesen** [comment] 2023-06-01 11:05
I am closing this issue as it seems like a Zabbix issue...

**Closed by yurtesen** 2023-06-01 11:05 UTC

**Comment by sandrobordacchini** [comment] 2024-01-18 10:11
FYI @yurtesen 

https://support.zabbix.com/browse/ZBX-22130?focusedId=889978&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-889978

**Comment by dkadioglu** [comment] 2024-08-08 07:21
> FYI @yurtesen
> 
> https://support.zabbix.com/browse/ZBX-22130?focusedId=889978&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-889978

Actually, I don't understand, if that last comment in the above issue means, that they will fix something in Zabbix or not. At least for me, the issue is, that the trigger fires although there is no error, if the rule is like it is in the current template:
```
length(last(/Template App BackupPC by Zabbix agent/backuppc.error.[{#HOST}]))<>0 and last(/Template App BackupPC by Zabbix agent/backuppc.disabled.[{#HOST}])=0
```
If I change that to the following, the trigger doesn't fire anymore, when there is no error (although I could not test so far, what happens when there is an error):
```
last(/Template App BackupPC by Zabbix agent/backuppc.error.[{#HOST}])<>"null" and last(/Template App BackupPC by Zabbix agent/backuppc.disabled.[{#HOST}])=0
```
Does anybody know more here? Is there still something to be changed in Zabbix or should there maybe changed something (e.g. like I did above) in this template?
